//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Liquidacion_de_Haberes.Models.DbModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext()
            : base("name=DbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bancos> bancos { get; set; }
        public virtual DbSet<categorias> categorias { get; set; }
        public virtual DbSet<cuentasBancarias> cuentasBancarias { get; set; }
        public virtual DbSet<depositos> depositos { get; set; }
        public virtual DbSet<empleados> empleados { get; set; }
        public virtual DbSet<obrasSociales> obrasSociales { get; set; }
        public virtual DbSet<sectores> sectores { get; set; }
    }
}
