//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Liquidacion_de_Haberes.Models.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuentasBancarias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cuentasBancarias()
        {
            this.empleados = new HashSet<empleados>();
        }
    
        public int idCuentasBancarias { get; set; }
        public int bancos_idbancos { get; set; }
        public long cbu { get; set; }
    
        public virtual bancos bancos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<empleados> empleados { get; set; }
    }
}
