//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Liquidacion_de_Haberes.Models.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class depositos
    {
        public int idDepositos { get; set; }
        public int empleados_idEmpleados { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual empleados empleados { get; set; }
    }
}
