//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Liquidacion_de_Haberes.Models.DbModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class empleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empleados()
        {
            this.depositos = new HashSet<depositos>();
        }
    
        public int idEmpleados { get; set; }

        [Display(Name = "NOMBRE")]
        public string nombre { get; set; }

        [Display(Name = "APELLIDO")]
        public string apellido { get; set; }

        [Display(Name = "LUGAR DE TRABAJO")]
        public string lugarTrabajo { get; set; }

        [Display(Name = "CUIL")]
        public string cuil { get; set; }

        [Display(Name = "LEGAJO")]
        public int legajo { get; set; }

        [Display(Name = "ANTIGÜEDAD")]
        public System.DateTime antiguedad { get; set; }

        [Display(Name = "FECHA DE INGRESO")]
        public System.DateTime fechaIngreso { get; set; }

        [Display(Name = "FECHA DE ENGRESO")]
        public Nullable<System.DateTime> fechaEgreso { get; set; }

        [Display(Name = "OBRA SOCIAL")]
        public int obrasSociales_idobrasSociales { get; set; }
        public int cuentasBancarias_idcuentasBancarias { get; set; }

        [Display(Name = "CATEGORÍA")]
        public int categorias_idcategorias { get; set; }

        [Display(Name = "ACTIVO")]
        public byte[] activo { get; set; }
    
        public virtual categorias categorias { get; set; }
        public virtual cuentasBancarias cuentasBancarias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<depositos> depositos { get; set; }
        public virtual obrasSociales obrasSociales { get; set; }
    }
}
